version: '3.1'

services:
  kotlindb:
    container_name: star-wars-database
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "star_wars_database"
    volumes:
      - D:\workspace\star_wars_database\mysql:/var/lib/mysql